server:
  port: ${PORT_SERVICE}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JHCTDEV/config_data.git
          #search-paths: config-data
      enabled: true

  security:
    user:
      name: root
      password: 123a