server:
  port: 8089
spring:
  data:
    mongodb:
      port: 27017
      uri: mongodb://localhost/customerProduct
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration:9093/eureka/

