server:
  port: 8082
spring:
  data:
    mongodb:
      port: 27017
      uri: mongodb://localhost/transaction
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9093/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost